site_name: Xorob0's docs
site_url: https://docs.gneee.tech
site_description: Documentation for my personal home lab
site_author: Xorob0

theme:
  name: material
  palette:
    scheme: preference
    accent: yellow
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
  font: false
  logo: assets/logo.svg
  favicon: assets/logo.svg


extra_css:
  - stylesheets/celty.css

markdown_extensions:
  - toc:
      permalink: ⚓︎
  - meta


plugins:
  - search
  - roamlinks 
