site_name: Celty's Docs
site_url: https://docs.gneee.tech
site_description: Docs for my personal HomeLab
site_author: Xorob0

theme:
  name: material
  palette:
    scheme: preference
    accent: yellow
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  font: false

extra_css:
  - stylesheets/celty.css

markdown_extensions:
  - toc:
      permalink: ⚓︎

nav:
  - "index.md"
  - "Show off":
      - "hardware.md"
      - "software.md"
  - "Services":
      - "services/template.md"
      - "services/caddy.md"
      - "Media Server":
          - "services/plex.md"
          - "services/tautulli.md"
          - "services/jackett.md"
          - "services/radarr.md"
          - "services/sonarr.md"
          - "services/bazarr.md"
          - "services/ombi.md"
      - "Torrents":
          - "services/qbittorrent.md"
          - "services/flood.md"
      - "services/portainer.md"
      - "services/miniflux.md"
      - "services/linx.md"
      - "services/librephotos.md"
      - "services/adguardhome.md"
      - "services/organizr.md"
      - "services/syncthing.md"
      - "services/vscode.md"
      - "services/sanoid.md"
      - "services/wireguard.md"
      - "Monitoring":
          - "services/prometheus.md"
  - "About":
      - "license.md"
