site_name: Celty's Docs
site_url: https://docs.gneee.tech
site_description: Docs for my personal HomeLab
site_author: Xorob0

theme:
  name: material
  palette:
    scheme: preference
    accent: yellow
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  font: false

extra_css:
  - stylesheets/celty.css

markdown_extensions:
  - toc:
      permalink: ⚓︎

nav:
  - "index.md"
  - "Overview":
      - "overview/servers.md"
      - "overview/homenetwork.md"
      - "overview/template.md"
      - "overview/ZFS.md"
      - "overview/docker.md"
  - "Celty":
      - "Host":
          - "celty/host/proxmox.md"
          - "celty/host/storage.md"
          - "celty/host/docker.md"
      - "Services":
          - "celty/services/plex.md"
          - "celty/services/radarr.md"
          - "celty/services/sonarr.md"
          - "celty/services/bazarr.md"
          - "celty/services/calibre.md"
          - "celty/services/tautulli.md"
          - "celty/services/torrents.md"
          - "celty/services/linx.md"
          - "celty/services/minio.md"
      - "Monitoring":
          - "celty/monitoring/cadvisor.md"
          - "celty/monitoring/node.md"
      - "Others":
          - "celty/others/portaineragent.md"
          - "celty/others/dns.md"
          - "celty/others/watchtower.md"
  - "Nimbus":
      - "Host":
          - "nimbus/host/VPS.md"
          - "nimbus/host/debian.md"
          - "nimbus/host/docker.md"
      - "Services":
          - "nimbus/services/synapse.md"
          - "nimbus/services/jackett.md"
          - "nimbus/services/miniflux.md"
          - "nimbus/services/ombi.md"
          - "nimbus/services/organizr.md"
          - "nimbus/services/portainer.md"
          - "nimbus/services/monitoring.md"
      - "Monitoring":
          - "nimbus/monitoring/cadvisor.md"
          - "nimbus/monitoring/node.md"
          - "nimbus/monitoring/blackhole.md"
      - "Others":
          - "celty/others/watchtower.md"
  - "Tinker":
      - "Host":
          - "tinker/host/raspberrypi.md"
          - "tinker/host/ubuntu.md"
          - "tinker/host/docker.md"
      - "Services":
          - "tinker/services/caddy.md"
          - "tinker/services/nextcloud.md"
          - "tinker/services/adguard.md"
      - "Monitoring":
          - "tinker/monitoring/cadvisor.md"
          - "tinker/monitoring/node.md"
  - "About":
      - "license.md"
